/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/go-remove/internal/trash"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTrasher creates a new instance of MockTrasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrasher {
	mock := &MockTrasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTrasher is an autogenerated mock type for the Trasher type
type MockTrasher struct {
	mock.Mock
}

type MockTrasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrasher) EXPECT() *MockTrasher_Expecter {
	return &MockTrasher_Expecter{mock: &_m.Mock}
}

// DeletePermanently provides a mock function for the type MockTrasher
func (_mock *MockTrasher) DeletePermanently(ctx context.Context, trashPath string) error {
	ret := _mock.Called(ctx, trashPath)

	if len(ret) == 0 {
		panic("no return value specified for DeletePermanently")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, trashPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTrasher_DeletePermanently_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePermanently'
type MockTrasher_DeletePermanently_Call struct {
	*mock.Call
}

// DeletePermanently is a helper method to define mock.On call
//   - ctx context.Context
//   - trashPath string
func (_e *MockTrasher_Expecter) DeletePermanently(ctx interface{}, trashPath interface{}) *MockTrasher_DeletePermanently_Call {
	return &MockTrasher_DeletePermanently_Call{Call: _e.mock.On("DeletePermanently", ctx, trashPath)}
}

func (_c *MockTrasher_DeletePermanently_Call) Run(run func(ctx context.Context, trashPath string)) *MockTrasher_DeletePermanently_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTrasher_DeletePermanently_Call) Return(err error) *MockTrasher_DeletePermanently_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTrasher_DeletePermanently_Call) RunAndReturn(run func(ctx context.Context, trashPath string) error) *MockTrasher_DeletePermanently_Call {
	_c.Call.Return(run)
	return _c
}

// GetTrashPath provides a mock function for the type MockTrasher
func (_mock *MockTrasher) GetTrashPath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTrashPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTrasher_GetTrashPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrashPath'
type MockTrasher_GetTrashPath_Call struct {
	*mock.Call
}

// GetTrashPath is a helper method to define mock.On call
func (_e *MockTrasher_Expecter) GetTrashPath() *MockTrasher_GetTrashPath_Call {
	return &MockTrasher_GetTrashPath_Call{Call: _e.mock.On("GetTrashPath")}
}

func (_c *MockTrasher_GetTrashPath_Call) Run(run func()) *MockTrasher_GetTrashPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTrasher_GetTrashPath_Call) Return(s string) *MockTrasher_GetTrashPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTrasher_GetTrashPath_Call) RunAndReturn(run func() string) *MockTrasher_GetTrashPath_Call {
	_c.Call.Return(run)
	return _c
}

// IsInTrash provides a mock function for the type MockTrasher
func (_mock *MockTrasher) IsInTrash(trashPath string) bool {
	ret := _mock.Called(trashPath)

	if len(ret) == 0 {
		panic("no return value specified for IsInTrash")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(trashPath)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTrasher_IsInTrash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsInTrash'
type MockTrasher_IsInTrash_Call struct {
	*mock.Call
}

// IsInTrash is a helper method to define mock.On call
//   - trashPath string
func (_e *MockTrasher_Expecter) IsInTrash(trashPath interface{}) *MockTrasher_IsInTrash_Call {
	return &MockTrasher_IsInTrash_Call{Call: _e.mock.On("IsInTrash", trashPath)}
}

func (_c *MockTrasher_IsInTrash_Call) Run(run func(trashPath string)) *MockTrasher_IsInTrash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTrasher_IsInTrash_Call) Return(b bool) *MockTrasher_IsInTrash_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTrasher_IsInTrash_Call) RunAndReturn(run func(trashPath string) bool) *MockTrasher_IsInTrash_Call {
	_c.Call.Return(run)
	return _c
}

// ListTrash provides a mock function for the type MockTrasher
func (_mock *MockTrasher) ListTrash() ([]trash.TrashEntry, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListTrash")
	}

	var r0 []trash.TrashEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]trash.TrashEntry, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []trash.TrashEntry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]trash.TrashEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrasher_ListTrash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTrash'
type MockTrasher_ListTrash_Call struct {
	*mock.Call
}

// ListTrash is a helper method to define mock.On call
func (_e *MockTrasher_Expecter) ListTrash() *MockTrasher_ListTrash_Call {
	return &MockTrasher_ListTrash_Call{Call: _e.mock.On("ListTrash")}
}

func (_c *MockTrasher_ListTrash_Call) Run(run func()) *MockTrasher_ListTrash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTrasher_ListTrash_Call) Return(trashEntrys []trash.TrashEntry, err error) *MockTrasher_ListTrash_Call {
	_c.Call.Return(trashEntrys, err)
	return _c
}

func (_c *MockTrasher_ListTrash_Call) RunAndReturn(run func() ([]trash.TrashEntry, error)) *MockTrasher_ListTrash_Call {
	_c.Call.Return(run)
	return _c
}

// MoveToTrash provides a mock function for the type MockTrasher
func (_mock *MockTrasher) MoveToTrash(ctx context.Context, filePath string) (string, error) {
	ret := _mock.Called(ctx, filePath)

	if len(ret) == 0 {
		panic("no return value specified for MoveToTrash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, filePath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, filePath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, filePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrasher_MoveToTrash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MoveToTrash'
type MockTrasher_MoveToTrash_Call struct {
	*mock.Call
}

// MoveToTrash is a helper method to define mock.On call
//   - ctx context.Context
//   - filePath string
func (_e *MockTrasher_Expecter) MoveToTrash(ctx interface{}, filePath interface{}) *MockTrasher_MoveToTrash_Call {
	return &MockTrasher_MoveToTrash_Call{Call: _e.mock.On("MoveToTrash", ctx, filePath)}
}

func (_c *MockTrasher_MoveToTrash_Call) Run(run func(ctx context.Context, filePath string)) *MockTrasher_MoveToTrash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTrasher_MoveToTrash_Call) Return(s string, err error) *MockTrasher_MoveToTrash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTrasher_MoveToTrash_Call) RunAndReturn(run func(ctx context.Context, filePath string) (string, error)) *MockTrasher_MoveToTrash_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreFromTrash provides a mock function for the type MockTrasher
func (_mock *MockTrasher) RestoreFromTrash(ctx context.Context, trashPath string, originalPath string) error {
	ret := _mock.Called(ctx, trashPath, originalPath)

	if len(ret) == 0 {
		panic("no return value specified for RestoreFromTrash")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, trashPath, originalPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTrasher_RestoreFromTrash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreFromTrash'
type MockTrasher_RestoreFromTrash_Call struct {
	*mock.Call
}

// RestoreFromTrash is a helper method to define mock.On call
//   - ctx context.Context
//   - trashPath string
//   - originalPath string
func (_e *MockTrasher_Expecter) RestoreFromTrash(ctx interface{}, trashPath interface{}, originalPath interface{}) *MockTrasher_RestoreFromTrash_Call {
	return &MockTrasher_RestoreFromTrash_Call{Call: _e.mock.On("RestoreFromTrash", ctx, trashPath, originalPath)}
}

func (_c *MockTrasher_RestoreFromTrash_Call) Run(run func(ctx context.Context, trashPath string, originalPath string)) *MockTrasher_RestoreFromTrash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTrasher_RestoreFromTrash_Call) Return(err error) *MockTrasher_RestoreFromTrash_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTrasher_RestoreFromTrash_Call) RunAndReturn(run func(ctx context.Context, trashPath string, originalPath string) error) *MockTrasher_RestoreFromTrash_Call {
	_c.Call.Return(run)
	return _c
}
