/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/go-remove/internal/cli/flags"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRemover creates a new instance of MockRemover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRemover(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRemover {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRemover{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRemover is an autogenerated mock type for the Remover type
type MockRemover struct {
	mock.Mock
}

type MockRemover_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRemover) EXPECT() *MockRemover_Expecter {
	return &MockRemover_Expecter{mock: &_m.Mock}
}

// Remove provides a mock function for the type MockRemover
func (_mock *MockRemover) Remove(ctx context.Context, binary string, settings flags.Settings) error {
	ret := _mock.Called(ctx, binary, settings)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, flags.Settings) error); ok {
		r0 = returnFunc(ctx, binary, settings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRemover_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockRemover_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - binary string
//   - settings flags.Settings
func (_e *MockRemover_Expecter) Remove(ctx any, binary any, settings any) *MockRemover_Remove_Call {
	return &MockRemover_Remove_Call{Call: _e.mock.On("Remove", ctx, binary, settings)}
}

func (_c *MockRemover_Remove_Call) Run(run func(ctx context.Context, binary string, settings flags.Settings)) *MockRemover_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 flags.Settings
		if args[2] != nil {
			arg2 = args[2].(flags.Settings)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRemover_Remove_Call) Return(err error) *MockRemover_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRemover_Remove_Call) RunAndReturn(run func(ctx context.Context, binary string, settings flags.Settings) error) *MockRemover_Remove_Call {
	_c.Call.Return(run)
	return _c
}
