/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/nicholas-fedor/go-remove/internal/logger"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type MockLogger
func (_mock *MockLogger) Debug(msg string, fields ...logger.Field) {
	if len(fields) > 0 {
		_mock.Called(msg, fields)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - msg string
//   - fields ...logger.Field
func (_e *MockLogger_Expecter) Debug(msg any, fields ...any) *MockLogger_Debug_Call {
	return &MockLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]any{msg}, fields...)...)}
}

func (_c *MockLogger_Debug_Call) Run(run func(msg string, fields ...logger.Field)) *MockLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []logger.Field
		var variadicArgs []logger.Field
		if len(args) > 1 {
			variadicArgs = args[1].([]logger.Field)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Debug_Call) Return() *MockLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debug_Call) RunAndReturn(run func(msg string, fields ...logger.Field)) *MockLogger_Debug_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type MockLogger
func (_mock *MockLogger) Error(msg string, fields ...logger.Field) {
	if len(fields) > 0 {
		_mock.Called(msg, fields)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - fields ...logger.Field
func (_e *MockLogger_Expecter) Error(msg any, fields ...any) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error",
		append([]any{msg}, fields...)...)}
}

func (_c *MockLogger_Error_Call) Run(run func(msg string, fields ...logger.Field)) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []logger.Field
		var variadicArgs []logger.Field
		if len(args) > 1 {
			variadicArgs = args[1].([]logger.Field)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(msg string, fields ...logger.Field)) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type MockLogger
func (_mock *MockLogger) Info(msg string, fields ...logger.Field) {
	if len(fields) > 0 {
		_mock.Called(msg, fields)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - fields ...logger.Field
func (_e *MockLogger_Expecter) Info(msg any, fields ...any) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]any{msg}, fields...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(msg string, fields ...logger.Field)) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []logger.Field
		var variadicArgs []logger.Field
		if len(args) > 1 {
			variadicArgs = args[1].([]logger.Field)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(msg string, fields ...logger.Field)) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// Level provides a mock function for the type MockLogger
func (_mock *MockLogger) Level(level logger.Level) {
	_mock.Called(level)
	return
}

// MockLogger_Level_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Level'
type MockLogger_Level_Call struct {
	*mock.Call
}

// Level is a helper method to define mock.On call
//   - level logger.Level
func (_e *MockLogger_Expecter) Level(level any) *MockLogger_Level_Call {
	return &MockLogger_Level_Call{Call: _e.mock.On("Level", level)}
}

func (_c *MockLogger_Level_Call) Run(run func(level logger.Level)) *MockLogger_Level_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 logger.Level
		if args[0] != nil {
			arg0 = args[0].(logger.Level)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogger_Level_Call) Return() *MockLogger_Level_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Level_Call) RunAndReturn(run func(level logger.Level)) *MockLogger_Level_Call {
	_c.Run(run)
	return _c
}

// SetCaptureFunc provides a mock function for the type MockLogger
func (_mock *MockLogger) SetCaptureFunc(captureFunc logger.LogCaptureFunc) {
	_mock.Called(captureFunc)
	return
}

// MockLogger_SetCaptureFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCaptureFunc'
type MockLogger_SetCaptureFunc_Call struct {
	*mock.Call
}

// SetCaptureFunc is a helper method to define mock.On call
//   - captureFunc logger.LogCaptureFunc
func (_e *MockLogger_Expecter) SetCaptureFunc(captureFunc any) *MockLogger_SetCaptureFunc_Call {
	return &MockLogger_SetCaptureFunc_Call{Call: _e.mock.On("SetCaptureFunc", captureFunc)}
}

func (_c *MockLogger_SetCaptureFunc_Call) Run(run func(captureFunc logger.LogCaptureFunc)) *MockLogger_SetCaptureFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 logger.LogCaptureFunc
		if args[0] != nil {
			arg0 = args[0].(logger.LogCaptureFunc)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogger_SetCaptureFunc_Call) Return() *MockLogger_SetCaptureFunc_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_SetCaptureFunc_Call) RunAndReturn(run func(captureFunc logger.LogCaptureFunc)) *MockLogger_SetCaptureFunc_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type MockLogger
func (_mock *MockLogger) Warn(msg string, fields ...logger.Field) {
	if len(fields) > 0 {
		_mock.Called(msg, fields)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - msg string
//   - fields ...logger.Field
func (_e *MockLogger_Expecter) Warn(msg any, fields ...any) *MockLogger_Warn_Call {
	return &MockLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]any{msg}, fields...)...)}
}

func (_c *MockLogger_Warn_Call) Run(run func(msg string, fields ...logger.Field)) *MockLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []logger.Field
		var variadicArgs []logger.Field
		if len(args) > 1 {
			variadicArgs = args[1].([]logger.Field)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Warn_Call) Return() *MockLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warn_Call) RunAndReturn(run func(msg string, fields ...logger.Field)) *MockLogger_Warn_Call {
	_c.Run(run)
	return _c
}
