/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/go-remove/internal/buildinfo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockExtractor creates a new instance of MockExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExtractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExtractor {
	mock := &MockExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExtractor is an autogenerated mock type for the Extractor type
type MockExtractor struct {
	mock.Mock
}

type MockExtractor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExtractor) EXPECT() *MockExtractor_Expecter {
	return &MockExtractor_Expecter{mock: &_m.Mock}
}

// CalculateChecksum provides a mock function for the type MockExtractor
func (_mock *MockExtractor) CalculateChecksum(binaryPath string) (string, error) {
	ret := _mock.Called(binaryPath)

	if len(ret) == 0 {
		panic("no return value specified for CalculateChecksum")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(binaryPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(binaryPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(binaryPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExtractor_CalculateChecksum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculateChecksum'
type MockExtractor_CalculateChecksum_Call struct {
	*mock.Call
}

// CalculateChecksum is a helper method to define mock.On call
//   - binaryPath string
func (_e *MockExtractor_Expecter) CalculateChecksum(binaryPath interface{}) *MockExtractor_CalculateChecksum_Call {
	return &MockExtractor_CalculateChecksum_Call{Call: _e.mock.On("CalculateChecksum", binaryPath)}
}

func (_c *MockExtractor_CalculateChecksum_Call) Run(run func(binaryPath string)) *MockExtractor_CalculateChecksum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExtractor_CalculateChecksum_Call) Return(s string, err error) *MockExtractor_CalculateChecksum_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockExtractor_CalculateChecksum_Call) RunAndReturn(run func(binaryPath string) (string, error)) *MockExtractor_CalculateChecksum_Call {
	_c.Call.Return(run)
	return _c
}

// Extract provides a mock function for the type MockExtractor
func (_mock *MockExtractor) Extract(ctx context.Context, binaryPath string) (*buildinfo.BuildInfoData, error) {
	ret := _mock.Called(ctx, binaryPath)

	if len(ret) == 0 {
		panic("no return value specified for Extract")
	}

	var r0 *buildinfo.BuildInfoData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*buildinfo.BuildInfoData, error)); ok {
		return returnFunc(ctx, binaryPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *buildinfo.BuildInfoData); ok {
		r0 = returnFunc(ctx, binaryPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*buildinfo.BuildInfoData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, binaryPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExtractor_Extract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extract'
type MockExtractor_Extract_Call struct {
	*mock.Call
}

// Extract is a helper method to define mock.On call
//   - ctx context.Context
//   - binaryPath string
func (_e *MockExtractor_Expecter) Extract(ctx interface{}, binaryPath interface{}) *MockExtractor_Extract_Call {
	return &MockExtractor_Extract_Call{Call: _e.mock.On("Extract", ctx, binaryPath)}
}

func (_c *MockExtractor_Extract_Call) Run(run func(ctx context.Context, binaryPath string)) *MockExtractor_Extract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExtractor_Extract_Call) Return(buildInfoData *buildinfo.BuildInfoData, err error) *MockExtractor_Extract_Call {
	_c.Call.Return(buildInfoData, err)
	return _c
}

func (_c *MockExtractor_Extract_Call) RunAndReturn(run func(ctx context.Context, binaryPath string) (*buildinfo.BuildInfoData, error)) *MockExtractor_Extract_Call {
	_c.Call.Return(run)
	return _c
}

// IsGoBinary provides a mock function for the type MockExtractor
func (_mock *MockExtractor) IsGoBinary(binaryPath string) bool {
	ret := _mock.Called(binaryPath)

	if len(ret) == 0 {
		panic("no return value specified for IsGoBinary")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(binaryPath)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockExtractor_IsGoBinary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsGoBinary'
type MockExtractor_IsGoBinary_Call struct {
	*mock.Call
}

// IsGoBinary is a helper method to define mock.On call
//   - binaryPath string
func (_e *MockExtractor_Expecter) IsGoBinary(binaryPath interface{}) *MockExtractor_IsGoBinary_Call {
	return &MockExtractor_IsGoBinary_Call{Call: _e.mock.On("IsGoBinary", binaryPath)}
}

func (_c *MockExtractor_IsGoBinary_Call) Run(run func(binaryPath string)) *MockExtractor_IsGoBinary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExtractor_IsGoBinary_Call) Return(b bool) *MockExtractor_IsGoBinary_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockExtractor_IsGoBinary_Call) RunAndReturn(run func(binaryPath string) bool) *MockExtractor_IsGoBinary_Call {
	_c.Call.Return(run)
	return _c
}
