/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockLister creates a new instance of MockLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLister {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockLister is an autogenerated mock type for the Lister type
type MockLister struct {
	mock.Mock
}

type MockLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLister) EXPECT() *MockLister_Expecter {
	return &MockLister_Expecter{mock: &_m.Mock}
}

// ListBinaries provides a mock function for the type MockLister
func (_mock *MockLister) ListBinaries(dir string) ([]string, error) {
	ret := _mock.Called(dir)

	if len(ret) == 0 {
		panic("no return value specified for ListBinaries")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(dir)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(dir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(dir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLister_ListBinaries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBinaries'
type MockLister_ListBinaries_Call struct {
	*mock.Call
}

// ListBinaries is a helper method to define mock.On call
//   - dir string
func (_e *MockLister_Expecter) ListBinaries(dir any) *MockLister_ListBinaries_Call {
	return &MockLister_ListBinaries_Call{Call: _e.mock.On("ListBinaries", dir)}
}

func (_c *MockLister_ListBinaries_Call) Run(run func(dir string)) *MockLister_ListBinaries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLister_ListBinaries_Call) Return(strings []string, err error) *MockLister_ListBinaries_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockLister_ListBinaries_Call) RunAndReturn(run func(dir string) ([]string, error)) *MockLister_ListBinaries_Call {
	_c.Call.Return(run)
	return _c
}
