/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/nicholas-fedor/go-remove/internal/logger"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRemover creates a new instance of MockRemover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRemover(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRemover {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRemover{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRemover is an autogenerated mock type for the Remover type
type MockRemover struct {
	mock.Mock
}

type MockRemover_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRemover) EXPECT() *MockRemover_Expecter {
	return &MockRemover_Expecter{mock: &_m.Mock}
}

// RemoveBinary provides a mock function for the type MockRemover
func (_mock *MockRemover) RemoveBinary(binaryPath string, name string, verbose bool, logger1 logger.Logger) error {
	ret := _mock.Called(binaryPath, name, verbose, logger1)

	if len(ret) == 0 {
		panic("no return value specified for RemoveBinary")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, bool, logger.Logger) error); ok {
		r0 = returnFunc(binaryPath, name, verbose, logger1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRemover_RemoveBinary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveBinary'
type MockRemover_RemoveBinary_Call struct {
	*mock.Call
}

// RemoveBinary is a helper method to define mock.On call
//   - binaryPath string
//   - name string
//   - verbose bool
//   - logger1 logger.Logger
func (_e *MockRemover_Expecter) RemoveBinary(binaryPath any, name any, verbose any, logger1 any) *MockRemover_RemoveBinary_Call {
	return &MockRemover_RemoveBinary_Call{Call: _e.mock.On("RemoveBinary", binaryPath, name, verbose, logger1)}
}

func (_c *MockRemover_RemoveBinary_Call) Run(run func(binaryPath string, name string, verbose bool, logger1 logger.Logger)) *MockRemover_RemoveBinary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 logger.Logger
		if args[3] != nil {
			arg3 = args[3].(logger.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRemover_RemoveBinary_Call) Return(err error) *MockRemover_RemoveBinary_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRemover_RemoveBinary_Call) RunAndReturn(run func(binaryPath string, name string, verbose bool, logger1 logger.Logger) error) *MockRemover_RemoveBinary_Call {
	_c.Call.Return(run)
	return _c
}
