/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/go-remove/internal/cli/flags"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBrowser creates a new instance of MockBrowser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBrowser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBrowser {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockBrowser{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockBrowser is an autogenerated mock type for the Browser type
type MockBrowser struct {
	mock.Mock
}

type MockBrowser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBrowser) EXPECT() *MockBrowser_Expecter {
	return &MockBrowser_Expecter{mock: &_m.Mock}
}

// BrowseHistory provides a mock function for the type MockBrowser
func (_mock *MockBrowser) BrowseHistory(ctx context.Context, settings flags.Settings) error {
	ret := _mock.Called(ctx, settings)

	if len(ret) == 0 {
		panic("no return value specified for BrowseHistory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, flags.Settings) error); ok {
		r0 = returnFunc(ctx, settings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBrowser_BrowseHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BrowseHistory'
type MockBrowser_BrowseHistory_Call struct {
	*mock.Call
}

// BrowseHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - settings flags.Settings
func (_e *MockBrowser_Expecter) BrowseHistory(ctx any, settings any) *MockBrowser_BrowseHistory_Call {
	return &MockBrowser_BrowseHistory_Call{Call: _e.mock.On("BrowseHistory", ctx, settings)}
}

func (_c *MockBrowser_BrowseHistory_Call) Run(run func(ctx context.Context, settings flags.Settings)) *MockBrowser_BrowseHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 flags.Settings
		if args[1] != nil {
			arg1 = args[1].(flags.Settings)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBrowser_BrowseHistory_Call) Return(err error) *MockBrowser_BrowseHistory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBrowser_BrowseHistory_Call) RunAndReturn(run func(ctx context.Context, settings flags.Settings) error) *MockBrowser_BrowseHistory_Call {
	_c.Call.Return(run)
	return _c
}
