/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/go-remove/internal/cli/flags"
	"github.com/nicholas-fedor/go-remove/internal/history"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUndoer creates a new instance of MockUndoer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUndoer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUndoer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockUndoer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockUndoer is an autogenerated mock type for the Undoer type
type MockUndoer struct {
	mock.Mock
}

type MockUndoer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUndoer) EXPECT() *MockUndoer_Expecter {
	return &MockUndoer_Expecter{mock: &_m.Mock}
}

// Undo provides a mock function for the type MockUndoer
func (_mock *MockUndoer) Undo(ctx context.Context, settings flags.Settings) (*history.RestoreResult, error) {
	ret := _mock.Called(ctx, settings)

	if len(ret) == 0 {
		panic("no return value specified for Undo")
	}

	var r0 *history.RestoreResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, flags.Settings) (*history.RestoreResult, error)); ok {
		return returnFunc(ctx, settings)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, flags.Settings) *history.RestoreResult); ok {
		r0 = returnFunc(ctx, settings)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*history.RestoreResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, flags.Settings) error); ok {
		r1 = returnFunc(ctx, settings)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUndoer_Undo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Undo'
type MockUndoer_Undo_Call struct {
	*mock.Call
}

// Undo is a helper method to define mock.On call
//   - ctx context.Context
//   - settings flags.Settings
func (_e *MockUndoer_Expecter) Undo(ctx any, settings any) *MockUndoer_Undo_Call {
	return &MockUndoer_Undo_Call{Call: _e.mock.On("Undo", ctx, settings)}
}

func (_c *MockUndoer_Undo_Call) Run(run func(ctx context.Context, settings flags.Settings)) *MockUndoer_Undo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 flags.Settings
		if args[1] != nil {
			arg1 = args[1].(flags.Settings)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUndoer_Undo_Call) Return(restoreResult *history.RestoreResult, err error) *MockUndoer_Undo_Call {
	_c.Call.Return(restoreResult, err)
	return _c
}

func (_c *MockUndoer_Undo_Call) RunAndReturn(run func(ctx context.Context, settings flags.Settings) (*history.RestoreResult, error)) *MockUndoer_Undo_Call {
	_c.Call.Return(run)
	return _c
}
