/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/go-remove/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorer creates a new instance of MockStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorer {
	mock := &MockStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorer is an autogenerated mock type for the Storer type
type MockStorer struct {
	mock.Mock
}

type MockStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorer) EXPECT() *MockStorer_Expecter {
	return &MockStorer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockStorer
func (_mock *MockStorer) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStorer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStorer_Expecter) Close() *MockStorer_Close_Call {
	return &MockStorer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStorer_Close_Call) Run(run func()) *MockStorer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorer_Close_Call) Return(err error) *MockStorer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Close_Call) RunAndReturn(run func() error) *MockStorer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllRecords provides a mock function for the type MockStorer
func (_mock *MockStorer) DeleteAllRecords(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllRecords")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_DeleteAllRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllRecords'
type MockStorer_DeleteAllRecords_Call struct {
	*mock.Call
}

// DeleteAllRecords is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorer_Expecter) DeleteAllRecords(ctx interface{}) *MockStorer_DeleteAllRecords_Call {
	return &MockStorer_DeleteAllRecords_Call{Call: _e.mock.On("DeleteAllRecords", ctx)}
}

func (_c *MockStorer_DeleteAllRecords_Call) Run(run func(ctx context.Context)) *MockStorer_DeleteAllRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorer_DeleteAllRecords_Call) Return(err error) *MockStorer_DeleteAllRecords_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_DeleteAllRecords_Call) RunAndReturn(run func(ctx context.Context) error) *MockStorer_DeleteAllRecords_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRecord provides a mock function for the type MockStorer
func (_mock *MockStorer) DeleteRecord(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRecord")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_DeleteRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRecord'
type MockStorer_DeleteRecord_Call struct {
	*mock.Call
}

// DeleteRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorer_Expecter) DeleteRecord(ctx interface{}, key interface{}) *MockStorer_DeleteRecord_Call {
	return &MockStorer_DeleteRecord_Call{Call: _e.mock.On("DeleteRecord", ctx, key)}
}

func (_c *MockStorer_DeleteRecord_Call) Run(run func(ctx context.Context, key string)) *MockStorer_DeleteRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_DeleteRecord_Call) Return(err error) *MockStorer_DeleteRecord_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_DeleteRecord_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockStorer_DeleteRecord_Call {
	_c.Call.Return(run)
	return _c
}

// GetMostRecent provides a mock function for the type MockStorer
func (_mock *MockStorer) GetMostRecent(ctx context.Context) (storage.HistoryRecord, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMostRecent")
	}

	var r0 storage.HistoryRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (storage.HistoryRecord, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) storage.HistoryRecord); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(storage.HistoryRecord)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_GetMostRecent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMostRecent'
type MockStorer_GetMostRecent_Call struct {
	*mock.Call
}

// GetMostRecent is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorer_Expecter) GetMostRecent(ctx interface{}) *MockStorer_GetMostRecent_Call {
	return &MockStorer_GetMostRecent_Call{Call: _e.mock.On("GetMostRecent", ctx)}
}

func (_c *MockStorer_GetMostRecent_Call) Run(run func(ctx context.Context)) *MockStorer_GetMostRecent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorer_GetMostRecent_Call) Return(historyRecord storage.HistoryRecord, err error) *MockStorer_GetMostRecent_Call {
	_c.Call.Return(historyRecord, err)
	return _c
}

func (_c *MockStorer_GetMostRecent_Call) RunAndReturn(run func(ctx context.Context) (storage.HistoryRecord, error)) *MockStorer_GetMostRecent_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecord provides a mock function for the type MockStorer
func (_mock *MockStorer) GetRecord(ctx context.Context, key string) (storage.HistoryRecord, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetRecord")
	}

	var r0 storage.HistoryRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (storage.HistoryRecord, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) storage.HistoryRecord); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(storage.HistoryRecord)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_GetRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecord'
type MockStorer_GetRecord_Call struct {
	*mock.Call
}

// GetRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorer_Expecter) GetRecord(ctx interface{}, key interface{}) *MockStorer_GetRecord_Call {
	return &MockStorer_GetRecord_Call{Call: _e.mock.On("GetRecord", ctx, key)}
}

func (_c *MockStorer_GetRecord_Call) Run(run func(ctx context.Context, key string)) *MockStorer_GetRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_GetRecord_Call) Return(historyRecord storage.HistoryRecord, err error) *MockStorer_GetRecord_Call {
	_c.Call.Return(historyRecord, err)
	return _c
}

func (_c *MockStorer_GetRecord_Call) RunAndReturn(run func(ctx context.Context, key string) (storage.HistoryRecord, error)) *MockStorer_GetRecord_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecords provides a mock function for the type MockStorer
func (_mock *MockStorer) ListRecords(ctx context.Context, opts storage.ListOptions) ([]storage.HistoryRecord, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListRecords")
	}

	var r0 []storage.HistoryRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.ListOptions) ([]storage.HistoryRecord, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.ListOptions) []storage.HistoryRecord); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.HistoryRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, storage.ListOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorer_ListRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecords'
type MockStorer_ListRecords_Call struct {
	*mock.Call
}

// ListRecords is a helper method to define mock.On call
//   - ctx context.Context
//   - opts storage.ListOptions
func (_e *MockStorer_Expecter) ListRecords(ctx interface{}, opts interface{}) *MockStorer_ListRecords_Call {
	return &MockStorer_ListRecords_Call{Call: _e.mock.On("ListRecords", ctx, opts)}
}

func (_c *MockStorer_ListRecords_Call) Run(run func(ctx context.Context, opts storage.ListOptions)) *MockStorer_ListRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.ListOptions
		if args[1] != nil {
			arg1 = args[1].(storage.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_ListRecords_Call) Return(historyRecords []storage.HistoryRecord, err error) *MockStorer_ListRecords_Call {
	_c.Call.Return(historyRecords, err)
	return _c
}

func (_c *MockStorer_ListRecords_Call) RunAndReturn(run func(ctx context.Context, opts storage.ListOptions) ([]storage.HistoryRecord, error)) *MockStorer_ListRecords_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRecord provides a mock function for the type MockStorer
func (_mock *MockStorer) SaveRecord(ctx context.Context, record *storage.HistoryRecord) error {
	ret := _mock.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for SaveRecord")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.HistoryRecord) error); ok {
		r0 = returnFunc(ctx, record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_SaveRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRecord'
type MockStorer_SaveRecord_Call struct {
	*mock.Call
}

// SaveRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - record storage.HistoryRecord
func (_e *MockStorer_Expecter) SaveRecord(ctx interface{}, record interface{}) *MockStorer_SaveRecord_Call {
	return &MockStorer_SaveRecord_Call{Call: _e.mock.On("SaveRecord", ctx, record)}
}

func (_c *MockStorer_SaveRecord_Call) Run(run func(ctx context.Context, record *storage.HistoryRecord)) *MockStorer_SaveRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *storage.HistoryRecord
		if args[1] != nil {
			arg1 = args[1].(*storage.HistoryRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_SaveRecord_Call) Return(err error) *MockStorer_SaveRecord_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_SaveRecord_Call) RunAndReturn(run func(ctx context.Context, record *storage.HistoryRecord) error) *MockStorer_SaveRecord_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRecord provides a mock function for the type MockStorer
func (_mock *MockStorer) UpdateRecord(ctx context.Context, record *storage.HistoryRecord) error {
	ret := _mock.Called(ctx, record)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecord")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.HistoryRecord) error); ok {
		r0 = returnFunc(ctx, record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_UpdateRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRecord'
type MockStorer_UpdateRecord_Call struct {
	*mock.Call
}

// UpdateRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - record storage.HistoryRecord
func (_e *MockStorer_Expecter) UpdateRecord(ctx interface{}, record interface{}) *MockStorer_UpdateRecord_Call {
	return &MockStorer_UpdateRecord_Call{Call: _e.mock.On("UpdateRecord", ctx, record)}
}

func (_c *MockStorer_UpdateRecord_Call) Run(run func(ctx context.Context, record *storage.HistoryRecord)) *MockStorer_UpdateRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *storage.HistoryRecord
		if args[1] != nil {
			arg1 = args[1].(*storage.HistoryRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_UpdateRecord_Call) Return(err error) *MockStorer_UpdateRecord_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_UpdateRecord_Call) RunAndReturn(run func(ctx context.Context, record *storage.HistoryRecord) error) *MockStorer_UpdateRecord_Call {
	_c.Call.Return(run)
	return _c
}
