/*
Copyright © 2026 Nicholas Fedor <nick@nickfedor.com>
SPDX-License-Identifier: AGPL-3.0-or-later
*/

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nicholas-fedor/go-remove/internal/history"
	mock "github.com/stretchr/testify/mock"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// ClearEntry provides a mock function for the type MockManager
func (_mock *MockManager) ClearEntry(ctx context.Context, entryID string, deleteFromTrash bool) error {
	ret := _mock.Called(ctx, entryID, deleteFromTrash)

	if len(ret) == 0 {
		panic("no return value specified for ClearEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, entryID, deleteFromTrash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_ClearEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearEntry'
type MockManager_ClearEntry_Call struct {
	*mock.Call
}

// ClearEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - entryID string
//   - deleteFromTrash bool
func (_e *MockManager_Expecter) ClearEntry(ctx interface{}, entryID interface{}, deleteFromTrash interface{}) *MockManager_ClearEntry_Call {
	return &MockManager_ClearEntry_Call{Call: _e.mock.On("ClearEntry", ctx, entryID, deleteFromTrash)}
}

func (_c *MockManager_ClearEntry_Call) Run(run func(ctx context.Context, entryID string, deleteFromTrash bool)) *MockManager_ClearEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManager_ClearEntry_Call) Return(err error) *MockManager_ClearEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_ClearEntry_Call) RunAndReturn(run func(ctx context.Context, entryID string, deleteFromTrash bool) error) *MockManager_ClearEntry_Call {
	_c.Call.Return(run)
	return _c
}

// ClearHistory provides a mock function for the type MockManager
func (_mock *MockManager) ClearHistory(ctx context.Context, clearTrash bool) error {
	ret := _mock.Called(ctx, clearTrash)

	if len(ret) == 0 {
		panic("no return value specified for ClearHistory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) error); ok {
		r0 = returnFunc(ctx, clearTrash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_ClearHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearHistory'
type MockManager_ClearHistory_Call struct {
	*mock.Call
}

// ClearHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - clearTrash bool
func (_e *MockManager_Expecter) ClearHistory(ctx interface{}, clearTrash interface{}) *MockManager_ClearHistory_Call {
	return &MockManager_ClearHistory_Call{Call: _e.mock.On("ClearHistory", ctx, clearTrash)}
}

func (_c *MockManager_ClearHistory_Call) Run(run func(ctx context.Context, clearTrash bool)) *MockManager_ClearHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_ClearHistory_Call) Return(err error) *MockManager_ClearHistory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_ClearHistory_Call) RunAndReturn(run func(ctx context.Context, clearTrash bool) error) *MockManager_ClearHistory_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockManager
func (_mock *MockManager) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockManager_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockManager_Expecter) Close() *MockManager_Close_Call {
	return &MockManager_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockManager_Close_Call) Run(run func()) *MockManager_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_Close_Call) Return(err error) *MockManager_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_Close_Call) RunAndReturn(run func() error) *MockManager_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePermanently provides a mock function for the type MockManager
func (_mock *MockManager) DeletePermanently(ctx context.Context, entryID string) error {
	ret := _mock.Called(ctx, entryID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePermanently")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, entryID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_DeletePermanently_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePermanently'
type MockManager_DeletePermanently_Call struct {
	*mock.Call
}

// DeletePermanently is a helper method to define mock.On call
//   - ctx context.Context
//   - entryID string
func (_e *MockManager_Expecter) DeletePermanently(ctx interface{}, entryID interface{}) *MockManager_DeletePermanently_Call {
	return &MockManager_DeletePermanently_Call{Call: _e.mock.On("DeletePermanently", ctx, entryID)}
}

func (_c *MockManager_DeletePermanently_Call) Run(run func(ctx context.Context, entryID string)) *MockManager_DeletePermanently_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_DeletePermanently_Call) Return(err error) *MockManager_DeletePermanently_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_DeletePermanently_Call) RunAndReturn(run func(ctx context.Context, entryID string) error) *MockManager_DeletePermanently_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistory provides a mock function for the type MockManager
func (_mock *MockManager) GetHistory(ctx context.Context, limit int) ([]*history.HistoryEntry, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 []*history.HistoryEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]*history.HistoryEntry, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []*history.HistoryEntry); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*history.HistoryEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_GetHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistory'
type MockManager_GetHistory_Call struct {
	*mock.Call
}

// GetHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockManager_Expecter) GetHistory(ctx interface{}, limit interface{}) *MockManager_GetHistory_Call {
	return &MockManager_GetHistory_Call{Call: _e.mock.On("GetHistory", ctx, limit)}
}

func (_c *MockManager_GetHistory_Call) Run(run func(ctx context.Context, limit int)) *MockManager_GetHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_GetHistory_Call) Return(historyEntrys []*history.HistoryEntry, err error) *MockManager_GetHistory_Call {
	_c.Call.Return(historyEntrys, err)
	return _c
}

func (_c *MockManager_GetHistory_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]*history.HistoryEntry, error)) *MockManager_GetHistory_Call {
	_c.Call.Return(run)
	return _c
}

// RecordDeletion provides a mock function for the type MockManager
func (_mock *MockManager) RecordDeletion(ctx context.Context, binaryPath string) (*history.HistoryEntry, error) {
	ret := _mock.Called(ctx, binaryPath)

	if len(ret) == 0 {
		panic("no return value specified for RecordDeletion")
	}

	var r0 *history.HistoryEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*history.HistoryEntry, error)); ok {
		return returnFunc(ctx, binaryPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *history.HistoryEntry); ok {
		r0 = returnFunc(ctx, binaryPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*history.HistoryEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, binaryPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_RecordDeletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordDeletion'
type MockManager_RecordDeletion_Call struct {
	*mock.Call
}

// RecordDeletion is a helper method to define mock.On call
//   - ctx context.Context
//   - binaryPath string
func (_e *MockManager_Expecter) RecordDeletion(ctx interface{}, binaryPath interface{}) *MockManager_RecordDeletion_Call {
	return &MockManager_RecordDeletion_Call{Call: _e.mock.On("RecordDeletion", ctx, binaryPath)}
}

func (_c *MockManager_RecordDeletion_Call) Run(run func(ctx context.Context, binaryPath string)) *MockManager_RecordDeletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_RecordDeletion_Call) Return(historyEntry *history.HistoryEntry, err error) *MockManager_RecordDeletion_Call {
	_c.Call.Return(historyEntry, err)
	return _c
}

func (_c *MockManager_RecordDeletion_Call) RunAndReturn(run func(ctx context.Context, binaryPath string) (*history.HistoryEntry, error)) *MockManager_RecordDeletion_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function for the type MockManager
func (_mock *MockManager) Restore(ctx context.Context, entryID string) (*history.RestoreResult, error) {
	ret := _mock.Called(ctx, entryID)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 *history.RestoreResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*history.RestoreResult, error)); ok {
		return returnFunc(ctx, entryID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *history.RestoreResult); ok {
		r0 = returnFunc(ctx, entryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*history.RestoreResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, entryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockManager_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - entryID string
func (_e *MockManager_Expecter) Restore(ctx interface{}, entryID interface{}) *MockManager_Restore_Call {
	return &MockManager_Restore_Call{Call: _e.mock.On("Restore", ctx, entryID)}
}

func (_c *MockManager_Restore_Call) Run(run func(ctx context.Context, entryID string)) *MockManager_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_Restore_Call) Return(restoreResult *history.RestoreResult, err error) *MockManager_Restore_Call {
	_c.Call.Return(restoreResult, err)
	return _c
}

func (_c *MockManager_Restore_Call) RunAndReturn(run func(ctx context.Context, entryID string) (*history.RestoreResult, error)) *MockManager_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// UndoMostRecent provides a mock function for the type MockManager
func (_mock *MockManager) UndoMostRecent(ctx context.Context) (*history.RestoreResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UndoMostRecent")
	}

	var r0 *history.RestoreResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*history.RestoreResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *history.RestoreResult); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*history.RestoreResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_UndoMostRecent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UndoMostRecent'
type MockManager_UndoMostRecent_Call struct {
	*mock.Call
}

// UndoMostRecent is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManager_Expecter) UndoMostRecent(ctx interface{}) *MockManager_UndoMostRecent_Call {
	return &MockManager_UndoMostRecent_Call{Call: _e.mock.On("UndoMostRecent", ctx)}
}

func (_c *MockManager_UndoMostRecent_Call) Run(run func(ctx context.Context)) *MockManager_UndoMostRecent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_UndoMostRecent_Call) Return(restoreResult *history.RestoreResult, err error) *MockManager_UndoMostRecent_Call {
	_c.Call.Return(restoreResult, err)
	return _c
}

func (_c *MockManager_UndoMostRecent_Call) RunAndReturn(run func(ctx context.Context) (*history.RestoreResult, error)) *MockManager_UndoMostRecent_Call {
	_c.Call.Return(run)
	return _c
}
