---
name: Run Security Checks
on:
  pull_request:
    branches: [main]
    paths:
      - cmd/**
      - internal/**
      - go.mod
      - go.sum
      - main.go
  push:
    branches: [main]

permissions:
  contents: read
  actions: read
  pull-requests: read
  security-events: write

env:
  GO_VERSION: 1.24.x
  OUTPUT_FILE: results.sarif

jobs:
  gosec:
    name: Golang Security Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Run Gosec Security Scanner
        uses: securego/gosec@2aaa9c41d6671d0ce7c778cc10340c4fd62d164b
        with:
          args: "-no-fail -fmt sarif -out results.sarif -tests ./..."
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@45775bd8235c68ba998cffa5171334d58593da47 # v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif

  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    steps:
      - id: govulncheck
        uses: nicholas-fedor/govulncheck-action@6a8d2de4ea206851920b33dd2e7058f9351556e7
        with:
          output-format: sarif
          output-file: ${{ env.OUTPUT_FILE }}
          go-version-input: ${{ env.GO_VERSION }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@45775bd8235c68ba998cffa5171334d58593da47 # v3
        with:
          sarif_file: ${{ env.OUTPUT_FILE }}
