---
name: Run Security Checks
on:
  pull_request:
    branches: [main]
    paths:
      - internal/**
      - go.mod
      - go.sum
      - main.go
  push:
    branches: [main]

env:
  OUTPUT_FILE: results.sarif

permissions:
  contents: read

jobs:
  gosec:
    name: Golang Security Checker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ccd8616d44fd3846e67624a50d5aad6d37bf2d25 # v2.22.1
        with:
          egress-policy: audit

      - name: Checkout Source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Run Gosec Security Scanner
        uses: securego/gosec@deb54465fea23d19a77f037e11e6589021f8501d # v2.29.0
        with:
          args: "-no-fail -fmt sarif -out results.sarif -tests ./..."
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@24c54180a607b1449ed407dd24f251e4e9147c8d # v4
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif

  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ccd8616d44fd3846e67624a50d5aad6d37bf2d25 # v2.22.1
        with:
          egress-policy: audit

      - id: govulncheck
        uses: nicholas-fedor/govulncheck-action@50174c98d9b5c00eb05ab498e09f91991df69e7d # v1.1.0
        with:
          output-format: sarif
          output-file: ${{ env.OUTPUT_FILE }}
          go-version-file: "go.mod"

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@24c54180a607b1449ed407dd24f251e4e9147c8d # v4
        with:
          sarif_file: ${{ env.OUTPUT_FILE }}
